imports:
    - { resource: parameters.yml }

dbs.options:
    silex_blog:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    console:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

db.migrations:
    directory: "%kernel.root_dir%/DoctrineMigrations"
    namespace: "DoctrineMigrations"
    name: "silex_blog"
    table_name: "_migrations"