imports:
    - { resource: parameters.yml }

dbs.options:
    default:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    console:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

routing:
    directory: "%kernel.root_dir%/config"

db.migrations:
    directory: "%kernel.root_dir%/migrations"
    namespace: "app\\migrations"
    name: "silex_blog"
    table_name: "_migrations"

fixtures:
    directory: "%kernel.root_dir%/fixtures"

jms.serializer:
    metadata_dir: "%kernel.root_dir%/serializer"

orm.em.options:
    mappings:
        Post:
            type: yml
            namespace: "Blog\\Entity\\Post"
            path: "%kernel.root_dir%/mappings"

