posts:
  path: /
  defaults:
    _controller: 'Blog\Controller\PostsController::createAction'
  methods: [POST]

posts.search:
  path: /
  defaults:
    _controller: 'Blog\Controller\PostsController::searchAction'
  methods: [GET]

posts.post:
  path: /{uuid}/
  defaults:
    _controller: 'Blog\Controller\PostsController::showAction'
  methods: [GET]

posts.post:
  path: /{uuid}/
  defaults:
    _controller: 'Blog\Controller\PostsController::editAction'
  methods: [PUT]

posts.post:
  path: /{uuid}/
  defaults:
    _controller: 'Blog\Controller\PostsController::deleteAction'
  methods: [DELETE]
