users.search:
  path: /
  defaults:
    _controller: 'Blog\Controller\UsersController::searchAction'
  methods: [GET]

users.user:
  path: /{id}/
  requirements:
    id: '\d+'
  defaults:
    _controller: 'Blog\Controller\UsersController::showAction'
  methods: [GET]

users.user:
  path: /{id}/
  requirements:
    id: '\d+'
  defaults:
    _controller: 'Blog\Controller\UsersController::editAction'
  methods: [PUT]
